module.exports = {
  PORT: 3000,
  MAX_PLAYERS: 4,
  MIN_PLAYERS: 2,
  AVAILABLE_CARS: 4,
  THROTTLE_RATE: 20,
  ROOM_CODE_LENGTH: 4,
  ROOM_CODE_CHARS: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
  ROOM_CODE_MAX_RETRIES: 5,
  PLAYER_ID_RESERVE_SECONDS: 30,
  COUNTDOWN_SECONDS: 3,
};